USE DW_COMERCIAL;

-- Creación sp_alter_stg_dim_categoria

CREATE PROCEDURE sp_alter_stg_dim_categoria
AS
BEGIN

	ALTER TABLE STG_DIM_CATEGORIA
	ALTER COLUMN COD_CATEGORIA VARCHAR(500);

	ALTER TABLE STG_DIM_CATEGORIA
	ALTER COLUMN DESC_CATEGORIA VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_categoria

EXEC sp_alter_stg_dim_categoria;




-- Creación sp_alter_stg_dim_cliente

CREATE PROCEDURE sp_alter_stg_dim_cliente
AS
BEGIN

	ALTER TABLE STG_DIM_CLIENTE
	ALTER COLUMN COD_CLIENTE VARCHAR(500);

	ALTER TABLE STG_DIM_CLIENTE
	ALTER COLUMN DESC_CLIENTE VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_cliente

EXEC sp_alter_stg_dim_cliente;



-- Creación sp_alter_stg_dim_pais

CREATE PROCEDURE sp_alter_stg_dim_pais
AS
BEGIN

	ALTER TABLE STG_DIM_PAIS
	ALTER COLUMN COD_PAIS VARCHAR(500);

	ALTER TABLE STG_DIM_PAIS
	ALTER COLUMN DESC_PAIS VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_pais

EXEC sp_alter_stg_dim_pais;



-- Creación sp_alter_stg_dim_producto

CREATE PROCEDURE sp_alter_stg_dim_producto
AS
BEGIN

	ALTER TABLE STG_DIM_PRODUCTO
	ALTER COLUMN COD_PRODUCTO VARCHAR(500);

	ALTER TABLE STG_DIM_PRODUCTO
	ALTER COLUMN DESC_PRODUCTO VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_producto

EXEC sp_alter_stg_dim_producto;



-- Creación sp_alter_stg_dim_sucursal

CREATE PROCEDURE sp_alter_stg_dim_sucursal
AS
BEGIN

	ALTER TABLE STG_DIM_SUCURSAL
	ALTER COLUMN COD_SUCURSAL VARCHAR(500);

	ALTER TABLE STG_DIM_SUCURSAL
	ALTER COLUMN DESC_SUCURSAL VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_sucursal

EXEC sp_alter_stg_dim_sucursal;



-- Creación sp_alter_stg_dim_vendedor

CREATE PROCEDURE sp_alter_stg_dim_vendedor
AS
BEGIN

	ALTER TABLE STG_DIM_VENDEDOR
	ALTER COLUMN COD_VENDEDOR VARCHAR(500);

	ALTER TABLE STG_DIM_VENDEDOR
	ALTER COLUMN DESC_VENDEDOR VARCHAR(500);

END;


-- Ejecución de sp_alter_stg_dim_vendedor

EXEC sp_alter_stg_dim_vendedor;



-- Modificación de los registros NULL de la columna COMISION_COMERCIAL

UPDATE STG_FACT_VENTAS
SET COMISION_COMERCIAL = 0.22 WHERE COMISION_COMERCIAL IS NULL;

-- Creación sp_alter_stg_fact_ventas

CREATE PROCEDURE sp_alter_stg_fact_ventas
AS
BEGIN
	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_PRODUCTO VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_CATEGORIA VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_CLIENTE VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_PAIS VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_VENDEDOR VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COD_SUCURSAL VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN FECHA VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN CANTIDAD_VENDIDA VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN MONTO_VENDIDO VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN PRECIO VARCHAR(500);

	ALTER TABLE STG_FACT_VENTAS
	ALTER COLUMN COMISION_COMERCIAL VARCHAR(500);
END;



-- Ejecución de sp_alter_stg_fact_ventas

EXEC sp_alter_stg_fact_ventas;




-- Creación de relaciones mediante FK en FACT_VENTAS

CREATE PROCEDURE sp_alter_fact_ventas
AS
BEGIN

ALTER TABLE [DW_COMERCIAL].DBO.FACT_VENTAS
ADD CONSTRAINT FK_CATEGORIA_VENTAS FOREIGN KEY ([CATEGORIA_KEY])
      REFERENCES DW_COMERCIAL.DBO.DIM_CATEGORIA (CATEGORIA_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_CLIENTE_VENTAS FOREIGN KEY (CLIENTE_KEY)
      REFERENCES DIM_CLIENTE (CLIENTE_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_PAIS_VENTAS FOREIGN KEY (PAIS_KEY)
      REFERENCES DIM_PAIS (PAIS_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_PRODUCTO_VENTAS FOREIGN KEY (PRODUCTO_KEY)
      REFERENCES DIM_PRODUCTO (PRODUCTO_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_SUCURSAL_VENTAS FOREIGN KEY (SUCURSAL_KEY)
      REFERENCES DIM_SUCURSAL (SUCURSAL_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_VENDEDOR_VENTAS FOREIGN KEY (VENDEDOR_KEY)
      REFERENCES DIM_VENDEDOR (VENDEDOR_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE FACT_VENTAS
ADD CONSTRAINT FK_TIEMPO_VENTAS FOREIGN KEY (TIEMPO_KEY)
      REFERENCES DIM_TIEMPO (TIEMPO_KEY)
      ON DELETE CASCADE
      ON UPDATE CASCADE;
	  
END  ;


-- Ejecución de sp_alter_fact_ventas

EXEC dbo.sp_alter_fact_ventas;




